variables:
    POI_REGISTRY: poi-registry:5000
    POI_IMAGE_BASE: ${POI_REGISTRY}/photon/installer:latest
    POI_IMAGE_NAME: ${POI_REGISTRY}/photon/installer:open-vmdk-$CI_COMMIT_SHORT_SHA
    GITHUB_BRANCH: master

stages:
- build
- test

build-container:
    stage: build
    needs: []
    script:
        - cd docker && docker build -t ${POI_IMAGE_NAME} --build-context open-vmdk=$(realpath $(pwd)/..) --build-arg POI_IMAGE=$POI_IMAGE_BASE -f Dockerfile-open-vmdk-tot .
        - docker push ${POI_IMAGE_NAME}
        - docker system prune -f

cayman_poi:
    stage: build
    needs: []
    script:
        - git clone --depth 1 https://:${POI_HARNESS_PULL_TOKEN}@${CI_SERVER_HOST}/photon/poi-harness.git
        - cd poi-harness
        - ./gitlab/submodule_ci.py --private-token=$CAYMAN_POI_CICD_API_TOKEN --project-id core-build/cayman_photon-os-installer --branch test/open-vmdk-submodule/$CI_COMMIT_SHORT_SHA --parent-branch vmware-master --submodule-path poi/open-vmdk --submodule-sha $CI_COMMIT_SHA

pytest:
    stage: test
    needs: []
    script:
        - make
        - pytest-3 pytest/
