stages:
- build
- test

cayman_poi:
    stage: build
    needs: []
    script:
        - git clone --depth 1 https://:${POI_HARNESS_PULL_TOKEN}@${CI_SERVER_HOST}/photon/poi-harness.git
        - cd poi-harness
        - ./gitlab/submodule_ci.py --private-token=$CAYMAN_POI_CICD_API_TOKEN --project-id core-build/cayman_photon-os-installer --branch test/open-vmdk-submodule/$CI_COMMIT_SHORT_SHA --parent-branch vmware-master --submodule-path poi/open-vmdk --submodule-sha $CI_COMMIT_SHA

pytest:
    stage: test
    script:
        - make
        - pytest-3 pytest/
