system:
    name: minimal
    type: vmx-14 vmx-20
    os_vmw: vmw.vmwarePhoton64Guest

networks:
    vm_network:
        name: "None"
        description: "The None network"

hardware:
    cpus: 2
    memory:
        type: memory
        size: 4096
    sata1:
        type: sata_controller
    cdrom1:
        type: cd_drive
        parent: sata1
    rootdisk:
        type: hard_disk
        parent: sata1
        disk_image: !param rootdisk=dummy.vmdk
        config:
            virtualDiskFormat: native_512
    usb1:
        type: usb_controller
    ethernet1:
        type: ethernet
        subtype: VmxNet3
        network: vm_network
        config:
            wakeOnLanEnabled: False
    videocard1:
        type: video_card
        config:
            enable3DSupport: true
            use3dRenderer : False
    vmci1:
        type: vmci
